# Generated by Django 5.1.3 on 2025-02-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('name', models.CharField(max_length=255)),
                ('skill_level', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('directions', models.CharField(blank=True, max_length=255)),
                ('proofs', models.ImageField(blank=True, null=True, upload_to='proofs/')),
            ],
        ),
    ]
