# Generated by Django 5.1.3 on 2025-02-18 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teacherad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherad',
            name='title',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherad',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
    ]
