# Generated by Django 5.1.3 on 2025-02-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_teacherad_title_alter_teacher_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAd',
        ),
    ]
