# Generated by Django 5.1.3 on 2025-02-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owned_items',
            field=models.ManyToManyField(blank=True, related_name='owners', to='main.shopitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_backgrounds', to='main.shopitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_frames', to='main.shopitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_icons', to='main.shopitem'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.CharField(choices=[('icon', 'Иконка'), ('background', 'Фон'), ('frame', 'Рамка')], default='icon', max_length=50),
        ),
    ]
